name: 'Ursula Busch - Bildhauerei '
favicon: null
layout_spectrum: 0.88322
typography_spectrum: 0.52316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#969db1'
    - '#586881'
    - '#6a7a94'
    - '#224155'
    - '#0f2b38'
  brandStrength: 0.625
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
