name: 'Ursula Busch - Bildhauerei '
favicon: null
layout_spectrum: 0.8423338735010475
typography_spectrum: 0.4209332645405084
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5807964452542365
  lightness: 0.8548545397352427
  saturation: 0.9815853494219482
  rhythmicContrast: 0.17021071957424283
purpose: []
